# Generated by Django 3.2.8 on 2021-11-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cop',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='cop',
            name='update_time',
        ),
    ]
