# Generated by Django 3.2.8 on 2021-11-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copinfo', '0002_auto_20211121_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cop',
            name='creditlevel',
            field=models.TextField(default='', verbose_name='信用水平'),
        ),
    ]
