# Generated by Django 3.2.9 on 2021-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='公司名称')),
                ('creditlevel', models.TextField(default='', verbose_name='信用水平')),
            ],
        ),
    ]
