# Generated by Django 3.2.9 on 2021-11-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin',
            old_name='name',
            new_name='copname',
        ),
    ]
